### ISSUE TITLE
登录信息过期后无法重新登录

### ISSUE THREAD

**Issue by Pearlulu** [Billyzou0741326/bilibili-raffle-js#14]
![image](https://user-images.githubusercontent.com/5378519/73444976-ac1ca280-4394-11ea-8bdf-abe607fc976d.png)
这之后就一直获取失败

然后重启程序也无法重新登录
![image](https://user-images.githubusercontent.com/5378519/73445067-dec69b00-4394-11ea-9949-3a0fb2e7bd4f.png)

应该是cookie满一个月过期了，手动删了user.json，可以正常登录，自动重新生成user.json。

新年快乐！

**Comment by Billyzou0741326** [comment]
新年快乐~
确实是bug 当时的确没写重登逻辑2333
