### ISSUE TITLE
linux下任务时间不是本地时间

### ISSUE THREAD

**Issue by Pearlulu** [Billyzou0741326/bilibili-raffle-js#2]
[2019-12-31 06:00:16]   626345       @10943409     GIFT_30405   33地图抽奖抽奖
date
Tue Dec 31 14:00:49 CST 2019

**Comment by Billyzou0741326** [comment]
也不对呢 是北京时间

**Comment by Billyzou0741326** [comment]
诶

**Comment by Billyzou0741326** [comment]
我用的 `process.env.TZ = 'Asia/Shanghai';` 在我这边测是没问题的... Windows倒是显示本地时间

**Comment by Billyzou0741326** [comment]
如果这个太不稳的话我就撤了 `process.env.TZ = '...'` 好了

**Comment by Pearlulu** [comment]
我用nvm切换了几个lts版node测试了下，process.env.TZ = 'Asia/Shanghai'在v4.9.1之前生效，v6.17.1以及之后的版本就没效果了。
![test](https://i.loli.net/2019/12/31/aVRquJS6E93BcxW.png)

**Comment by Billyzou0741326** [comment]
太强了… 大佬

**Comment by Billyzou0741326** [comment]
我得仔细研究下timezone看看时段怎么改

**Comment by Pearlulu** [comment]
好像new Date().toString()或者new Date().toLocalString()都是显示本地时间

**Comment by Billyzou0741326** [comment]
本地时间的话就可以很直接的
```javascript
new Date().getHours()
new Date().getMinutes()
```

**Comment by Billyzou0741326** [comment]
不过我的那个timeperiod和clock说不定要改 睡醒看下吧

**Comment by Billyzou0741326** [comment]
被大佬解决了 接下来任务一概按照北京时间设置/运行

**Comment by Pearlulu** [comment]
反正B站服务器是按北京时间来的，都按北京时间最好了

**Comment by Pearlulu** [comment]
> 被大佬解决了 接下来任务一概按照北京时间设置/运行

忽然又发现一个不是BUG的任务时间格式问题，配置文件里个位数时间前不能加0，以前写时间格式个位数的前面习惯加个0了。

**Comment by Billyzou0741326** [comment]
json的number不给加0... 不然格式错误了
