### ISSUE TITLE
服务端好像挂了？

### ISSUE THREAD

**Issue by Alkitor** [Billyzou0741326/bilibili-raffle-js#33]
突然连不上服务器了

**Comment by Billyzou0741326** [comment]
炸了23333
dns迁移太慢 估计几个小时都不一定更新好

**Comment by Billyzou0741326** [comment]
本地配置一下服务器 https://github.com/Billyzou0741326/bilibili-live-monitor-ts
然后这边的设置
https://github.com/Billyzou0741326/bilibili-raffle-js/blob/971b1418a29d7a19eaf13c713a4b91086344879f/src/settings.json#L6-L11
第8行的host改成"127.0.0.1"吧

ps 我自己也连不上2333

**Comment by Billyzou0741326** [comment]
已修复
