### ISSUE TITLE
app端的access_tokens咋搞啊，账号登录成功，但是没有app端的access_tokens

### ISSUE THREAD

**Issue by tlj218** [Billyzou0741326/bilibili-raffle-js#38]
是不是应该账号登录成功后自动获取的么，还是哪里需要搞一下，我是按照教程一步一步搞的，
另外TS监控服务器倒是成功了，TS和JS两个也是相互传输数据成功，就是没有app端的access_tokens不执行任务

**Comment by Billyzou0741326** [comment]
`src/client/default-user-info.json` username和password填一下 其它留空就行

**Comment by tlj218** [comment]
就是这样操作的啊，就是没反应

**Comment by Billyzou0741326** [comment]
显示登录成功的话 看一下`src/client/user.json`的内容 有漏的话那就不对了
不对的话删一下文件重新运行吧 刚测了登录没什么问题
