### ISSUE TITLE
登录出问题了

### ISSUE THREAD

**Issue by like044041** [Billyzou0741326/bilibili-raffle-js#41]
TypeError: Cannot read property 'cookies' of undefined
会显示这个

**Comment by Billyzou0741326** [comment]
第几行的报错

**Comment by like044041** [comment]
![image](https://user-images.githubusercontent.com/33434924/78847132-80770200-7a40-11ea-8813-c79fe41e83ca.png)
就是这样的

**Comment by Billyzou0741326** [comment]
如果能复现的话, 改一下代码再运行一次: 
https://github.com/Billyzou0741326/bilibili-raffle-js/blob/fffc1f991cac279795c28c34ac2fb034291c92d8/src/client/account.js#L117-L119
改成
```javascript
if (code !== 0) { 
    result = Promise.reject(`${code} - ${msg}`); 
} else {
    console.log(resp);
}
```
看下输出内容

**Comment by like044041** [comment]
我知道问题出在哪里了,我把设备验证打开了 不用麻烦你了老哥

**Comment by Billyzou0741326** [comment]
OK 应该是设备验证开启的情况下返回值正常但不带cookies信息
代码太不稳了2333
