### ISSUE TITLE
突然运行出错

### ISSUE THREAD

**Issue by skingorz** [Billyzou0741326/bilibili-raffle-js#45]
突然运行出错，状态码412 
![image](https://user-images.githubusercontent.com/36142776/80819898-75ab2980-8c08-11ea-8801-3e6432d5f121.png)

**Comment by Billyzou0741326** [comment]
412是请求频率过高或者单ip多号请求造成的

https://github.com/Billyzou0741326/bilibili-raffle-js/blob/1d83611d2dd5724e3598827068f83625f5aad972/src/bilibili/bilibili-rest.js#L175
1000不变 30下调到合适的数值吧 具体多少比较合适我也不清楚
现在是最多30请求1秒

**Comment by skingorz** [comment]
> 412是请求频率过高或者单ip多号请求造成的
> 
> https://github.com/Billyzou0741326/bilibili-raffle-js/blob/1d83611d2dd5724e3598827068f83625f5aad972/src/bilibili/bilibili-rest.js#L175
> 
> 
> 1000不变 30下调到合适的数值吧 具体多少比较合适我也不清楚
> 现在是最多30请求1秒

我刚刚又看了一下，什么没动，他现在自己正常运行了，谢谢啦

**Comment by Billyzou0741326** [comment]
嗯 客气了 一般最多1个小时解封ip
