### ISSUE TITLE
监控挂了吗

### ISSUE THREAD

**Issue by Jolkssn** [Billyzou0741326/bilibili-raffle-js#46]
14：44之前还是正常的，之后就没有一点儿动静了，无论怎么重开脚本，都只有
 [ Server ] Established connection with ws://bili.minamiktr.com/ws
这样一条成功连接的提示，之后就没有任何动静了

**Comment by like044041** [comment]
我这里也是这样,估计是挂了

**Comment by Jolkssn** [comment]
> 我这里也是这样,估计是挂了

看来是的呢

**Comment by lovezm** [comment]
炸了 等修复



hello.ergou@gmail.com
 
发件人： Jolkssn
发送时间： 2020-05-19 20:38
收件人： Billyzou0741326/bilibili-raffle-js
抄送： Subscribed
主题： Re: [Billyzou0741326/bilibili-raffle-js] 监控挂了吗 (#46)
我这里也是这样,估计是挂了
看来是的呢

**Comment by lovezm** [comment]
可先用 open.api.bili.ws:8999

**Comment by Billyzou0741326** [comment]
1
